Tic tac
maria-salmasian/TicTacToe pull request #2
Opened 2020-07-25 13:56 UTC by maria-salmasian

the game Tic Tac Toe

2020-07-25 20:03 UTC, hhov88 commented on GameTicTacToe/src/StageTwoDemo.java
> +        String game[][] = new String[3][3];
@maria-salmasian I think you cane make a some kind of object instead of use String array

2020-07-25 20:03 UTC, hhov88 commented on GameTicTacToe/src/TicTacToeStageOne.java
> +        String Won = "";
fields name always start by lowercase

2020-07-25 20:03 UTC, hhov88 commented on GameTicTacToe/src/TicTacToeStageTwo.java
> +        this.game[0][0] = game[0][0];
@maria-salmasian if game length is less then your class level game field ?

2020-07-26 12:25 UTC, nsimonyan requested changes

2020-07-26 12:25 UTC, nsimonyan commented on .gitignore
> +/production/GameTicTacToe/StageOneDemo.class
@maria-salmasian jan don't exclude seperatly each class

2020-07-26 12:25 UTC, nsimonyan commented on GameTicTacToe/src/TicTacToeStageOne.java
> +                    Won = game[0][1] + game[1][1] + game[2][1];
@maria-salmasian jan you can have a method and call it with different parameters instead of writing the same logic in all cases

2020-07-26 12:25 UTC, nsimonyan commented on GameTicTacToe/src/StageTwoDemo.java
> +public class StageTwoDemo {
@maria-salmasian jan please add comments

2022-11-30 12:53 UTC, merged